### PR TITLE
[color-scale][color-chart] Export the `gamut` part and hide it in charts, fixes #130

### LINKED ISSUE #130: [color-charts] Gamut badges should be hidden
image

The underlying `<color-swatch>`es display gamut badges if the gamut differs from `sRGB`. In color charts, there is no need for them.

### PR DESCRIPTION
**Pull request by DmitrySharabin**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Not sure if we should hide it or just make it way smaller.

**Comment by DmitrySharabin** [comment]
> Not sure if we should hide it or just make it way smaller.

I'm not sure if it's a valid option, but might we combine it with the rest of the information we have about the color (label, coords, etc.)?

**Comment by LeaVerou** [comment]
That would be much harder to implement. Can you try making it smaller (via `font-size`) and see how it looks?

**Comment by DmitrySharabin** [comment]
> That would be much harder to implement. Can you try making it smaller (via `font-size`) and see how it looks?

Here is how it looks with `font-size: 50%`:

image

**Comment by LeaVerou** [comment]
I think even smaller than that might work (40%?), and let's make sure to expose it as a part on `color-chart` so that people can easily hide it.

**Comment by DmitrySharabin** [comment]
> I think even smaller than that might work (40%?)

I think it does indeed:

image


> let's make sure to expose it as a part on `color-chart` so that people can easily hide it.

If I get it right, we have it in this PR.

**Review by LeaVerou — APPROVED** [review]
LGTM but let's fix the text color on that gamut badge!

**Pull request merged**
